# Generated by Django 4.1.2 on 2022-12-19 07:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Company',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_name', models.CharField(default='', max_length=256)),
                ('property_type', models.CharField(choices=[('PEB', 'PEB'), ('COLD STORAGE', 'COLD STORAGE'), ('RCC', 'RCC'), ('SHED', 'SHED'), ('OTHER', 'OTHER')], max_length=200, verbose_name='warehouse type')),
                ('property_survey_number', models.CharField(default=uuid.uuid4, max_length=36)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_properties', to='warehouse.company')),
            ],
            options={
                'verbose_name_plural': 'Property',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Gala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gala_number', models.CharField(default=uuid.uuid4, max_length=60, unique=True)),
                ('is_allotted', models.BooleanField(default=False)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_gala', to='warehouse.property')),
            ],
            options={
                'verbose_name_plural': 'Gala',
                'ordering': ('-created_at',),
            },
        ),
    ]
