# Generated by Django 4.1.2 on 2022-12-19 07:24

import contract.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_gala_detail', to='warehouse.gala')),
                ('owner', models.ForeignKey(default=contract.models.get_main_owner, on_delete=django.db.models.deletion.CASCADE, related_name='get_owner_contract', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Contract',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract.contract')),
                ('agreement_type', models.CharField(default='Leave_and_License', max_length=255)),
                ('agreement_valid_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contract', to='account.rental')),
            ],
            options={
                'verbose_name_plural': 'Contract With Rental',
            },
            bases=('contract.contract',),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract.contract')),
                ('agreement_type', models.CharField(default='Saledeed', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_contract', to='account.investor')),
            ],
            options={
                'verbose_name_plural': 'Contract With Investor',
            },
            bases=('contract.contract',),
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('contract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contract.contract')),
                ('agreement_type', models.CharField(default='Development', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_contract', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contract With Farmer',
            },
            bases=('contract.contract',),
        ),
    ]
