# Generated by Django 4.1.2 on 2022-12-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='gala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_gala_detail', to='warehouse.gala'),
        ),
    ]
